export const DEFAULT_SHADOW_NAMES = [
  "adam", "adela", "adriana", "alena", "ales", "albert", "alica", "alex", "alexander", "alexandra", "alexej", "alfred", "alzbeta", "amalia",
  "andrea", "andrej", "aneta", "anicka", "anita", "anna", "antonia", "anton", "augustin", "aurora",
  "barbora", "bartolomej", "beata", "benedikt", "bernard", "blazej", "bohdan", "bohumil", "bohus", "bohuslav", "boris", "branislav", "brano", "bronislava",
  "cecilia", "cyril",
  "dalibor", "daniel", "dano", "daria", "darina", "david", "denis", "denisa", "diana", "dobroslav", "dominik", "dominika", "dorota", "drahomir", "drahomira", "dusan", "dusko",
  "eduard", "ela", "elena", "eliska", "ema", "emil", "emilia", "erik", "erika", "eugen", "eva",
  "filip", "frantisek", "fero",
  "gabriel", "gabriela", "gizela", "gregor", "gustav",
  "hana", "hanka", "helena", "henrieta", "henrich", "hubert", "hugo",
  "igor", "imrich", "ivan", "ivana", "iveta", "ivona", "izabela",
  "jakub", "jana", "jan", "jano", "janko", "jarmila", "jaroslav", "jaroslava", "juraj", "julius", "julia", "juliana", "jurina", "justina",
  "kamil", "karol", "karolina", "katarina", "katka", "klara", "klaudia", "kornel", "kristian", "kristina", "kvetoslava",
  "laura", "lenka", "leonard", "leona", "liana", "lidia", "linda", "lucia", "lucian",
  "ludmila", "ludovit", "luba", "lubica", "lubomir", "lubomira", "lubor", "lubos",
  "magdalena", "malvina", "marcel", "marek", "margareta", "maria", "marian", "marianna", "marika", "marina", "marko", "marta", "martin", "martina", "maruska",
  "matej", "matus", "maxim", "maximilian", "melania", "metod",
  "michal", "michaela", "milada", "milana", "milan", "milena", "milos", "miloslava", "miriama", "miroslav", "miroslava", "monika",
  "natalia", "natasa", "nela", "nikola", "nikolas", "nina", "norbert",
  "oliver", "olga", "ondrej", "oskar", "otilia", "otto",
  "patricia", "patrik", "pavol", "pavel", "pavla", "pavlina", "peter", "petra", "peto",
  "radka", "radomir", "radovan", "rado", "rastislav", "rebeka", "renata", "rene", "richard", "robert", "roland", "romana", "roman", "rozalia", "rudolf",
  "sabina", "samuel", "samo", "sara", "sebastian", "silvia", "simona", "slavomir", "slavomira",
  "stanislav", "stano", "stefan", "stela",
  "tadeas", "tamara", "tatiana", "teodor", "terezia", "terka", "timotej", "tobias", "tomas", "tomi",
  "urban",
  "valent", "valeria", "valentyna", "vanda", "vera", "veronika", "viera", "viktor", "viktoria", "vincent", "viliam",
  "vladimir", "vladimira", "vladislav", "vojtech",
  "xaver", "xenia",
  "zdenek", "zdenko", "zdenka", "zita", "zlata", "zlatko", "zora", "zuzana", "zuzka", "zoska",
];
